# Generated by Django 3.2.9 on 2021-11-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Certificate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
