# Generated by Django 3.2.9 on 2021-11-28 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Certificate', '0002_alter_participant_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='Image',
        ),
        migrations.AddField(
            model_name='image',
            name='Img',
            field=models.ImageField(default='media/Certificate 1.png', upload_to='media/'),
        ),
        migrations.AddField(
            model_name='participant',
            name='Imagee',
            field=models.ForeignKey(default='media/Certificate 1.png', on_delete=django.db.models.deletion.CASCADE, to='Certificate.image'),
        ),
    ]
