# Generated by Django 3.2.9 on 2021-11-28 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Certificate', '0003_auto_20211128_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='Img',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='Imagee',
        ),
        migrations.AddField(
            model_name='image',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='participant',
            name='Image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Certificate.image'),
        ),
    ]
