# Generated by Django 3.2.9 on 2021-11-28 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Certificate', '0004_auto_20211128_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='Image',
        ),
    ]
