# Generated by Django 3.2.9 on 2021-11-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='participant',
            fields=[
                ('Pre', models.TextField()),
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=300)),
                ('Email', models.CharField(max_length=300)),
            ],
        ),
    ]
