# Generated by Django 3.2.9 on 2021-11-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Certificate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='image',
            field=models.ImageField(default='media/Certificate 5.png', upload_to='media/'),
        ),
    ]
