# Generated by Django 3.2.9 on 2021-11-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Certificate', '0002_participant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='image',
            field=models.ImageField(default='static/media/Certificate 5.png', upload_to='static/media/'),
        ),
    ]
