# Generated by Django 3.2.9 on 2021-11-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Certificate', '0003_alter_participant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='image',
            field=models.ImageField(default='media/Certificate 5.png', upload_to='media/'),
        ),
    ]
