# Generated by Django 3.2.9 on 2021-12-02 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Certificate', '0005_alter_participant_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pro', models.CharField(max_length=255)),
                ('inf', models.CharField(max_length=255)),
                ('Vple', models.CharField(max_length=255)),
                ('Participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Certificate.participant')),
            ],
        ),
    ]
