# Generated by Django 3.2.9 on 2021-12-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Certificate', '0006_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='Pro',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Medium', 'Medium'), ('Poor', 'Poor')], max_length=255),
        ),
    ]
