# Generated by Django 3.2.9 on 2021-12-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Certificate', '0007_alter_rating_pro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='Vple',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Medium', 'Medium'), ('Poor', 'Poor')], max_length=255),
        ),
        migrations.AlterField(
            model_name='rating',
            name='inf',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Medium', 'Medium'), ('Poor', 'Poor')], max_length=255),
        ),
    ]
