# Generated by Django 3.2.9 on 2021-12-02 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Certificate', '0008_auto_20211202_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='Pro',
            new_name='Informative',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='Vple',
            new_name='Professional',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='inf',
            new_name='VisuallyPleasing',
        ),
    ]
